language: node_js
node_js:
- 9.4.0
script:
- yarn run test
- yarn run build
after_success:
- npm run test:after_build
- yarn run coveralls
- yarn run codecov
deploy:
  provider: npm
  email: a@wyr.me
  api_key:
    secure: SGWoa8TY7r6Ksp1wDe3eXBOXmkKB5TGAS0Irqo6fgtmBW8oZ0IDBScxoDtgqQOknPhuhpfn8iwBaG/u+Pn3zHmFze9CqfrCWFfePVVo1uJEOV3SJrJZdl80GS9lDkaN3cBXcDKdVLIr5e8ZIID6fzlax8Is9Nxi6ZUnw8XFRiJ1EGreZ/KFfvRJWYuhM8mLlG5NT63syn1JzXEhsaOBCL8m+sXwoFCufdkuB332PJSuDvl0IhhH0sXG12H6R9ZWqXhGqEXqSvmEbAIsnxuzDzmxM/8nrvWT3TcDna9CjwpTzRccD9KLBNYxk6BIBnvjeAn8xjWFinwWk0vhr7mG19xY2GSA4bhrqUrMduRwUfB1YIoweh/1HdhlRl3Adj73OZON+O6mhX0tpWtBCyYQeksXXNbPNgcmga5k78CPtpUutswRhCOS1dmWMVQ+/so5P1d8bAPmG+YqcyNgFhJXjSD1a3wEzLRo7EQIeIDzyAe2cG+TQwoDTLW2Cn5xnBDmzmVCPIGF2SBi3i2ec74tNknDR2JRzcGlqZXj0xzZzF7u+0XwEB2e21JlZyB+GcH8DZu2Xa3Y3yFT1JzomT06giptAucxw/y0nspGA/+znLU5D6mKBkOmaaatbCejVekm+4aAgRiWkBxS0I4xDE+xGPxLRm84gfqQ6THzF4683COY=
  skip_cleanup: true
  on:
    tags: true
    repo: yi-ge/js-tree-list
  provider: releases
  api_key:
    secure: W8wkSYvZjpXi8QV/apgatLuDgeceMrlq3A79FgpOAhG27bgV7N43zkbjV9RSSjZiVWJ0oZnSgHQ0Qic1P6rN7iJPmm2AY70rA6pYoE2rdb3H2NAa1n4+STDmLIgeDLZW6dAVdbOQU48W8fKBjaVgjGbRZAhu++Llalsd30QDBW64pkiCYaatxvikhzNbr4P1nhDJyJl/gUnBbKspXRpGMb8BfY9exT2LPUXM+fQSExcEjLVhkRsTVkBh3Jk61Rj55gw9wCuQxHWjTzuss870fBNkHUYxfLaBs8NGkRpMJ1ER4NrVav872KStAjnyYZobqNqHE3P2SuwCnAhfJC0xXgQnzPIjhAnQqe6X4iSbR9RHSo7VBPdAkBH3zh79amJUi0o7gh2a/cWsGE/+8HGM/D6BsNdUJ5KjAY1cyk2iJkHTP8pJpexoQELFnw9iX+7ZwxL4x0dSa/B6IzM/90dQQIAxBKAZ8L0G469hMMH4OOQdfmWwznVICotOAkkBuYNZazbslJd4fA2BpGPmb+YIGjNkM7hdp39NUJr8Fu1fCOvxzxTw1pzZqRmX3O39b+fRYw06PIeW2j2qzJPogyGR9I3Nl2TrKqj4Irt91FtUF3vLj2LQO5cg8rftgNRgR4JcZfilBtoudBKrAoqyWju62rxf4xllPbvbljAvjsKBI+M=
  file: bin/js-tree-list.min.js
  skip_cleanup: true
  on:
    tags: true
    repo: yi-ge/js-tree-list
