language: node_js
node_js:
  - 9.4.0
install:
  - yarn add global rollup
  - yarn
script:
  - yarn run test
  - yarn run build
after_success:
  - npm run test:after_build
  - yarn run coveralls
  - yarn run codecov

